In [7]:
class Employee:#Employee class
    empCount=0 ##employeeCount is used to keep track of number of employee objects
    salSum=0 #salSum is used to take the average of the salaries of the Employee object 
    def __init__(self,name,family,salary,department): #constructor for Employee as per the requirements
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1
        Employee.salSum+=self.salary
    def avg(self):
        return Employee.salSum/Employee.empCount
    def displayEmployee(self):#another function for employee class
        print("Name :", self.name, ", Family:", self.family , ", Salary:", self.salary, ", Department:",self.department)

emp1 = Employee("Akhilesh","CM",2000,"CyberSecurity")#Employee objects creation with intialization
emp2 = Employee("Pooja","Cheekati",5000,"Hardware")
print("avg:",emp2.avg())#calling average function

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)

akhil=FulltimeEmployee("Kaushik","Reddy",9000,"IT")#FultimeEmployee object
akhil.displayEmployee()


avg: 3500.0
Name : Kaushik , Family: Reddy , Salary: 9000 , Department: IT


In [2]:
import numpy as np #importing numpy library
vec=np.arange(1,21,dtype=float)
print(vec)
vec=vec.reshape(4,5)
print(vec)
vec=np.where(np.isin(vec,vec.max(axis=1)),0,vec)
vec

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20.]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]]


array([[ 1.,  2.,  3.,  4.,  0.],
       [ 6.,  7.,  8.,  9.,  0.],
       [11., 12., 13., 14.,  0.],
       [16., 17., 18., 19.,  0.]])